---
- name: Prepare
  hosts: all
  gather_facts: false
  tasks:
    - name: Install Python and curl for Debian/Ubuntu
      raw: |
        apt-get update
        DEBIAN_FRONTEND=noninteractive apt-get install -y python3 curl
      changed_when: false
      args:
        executable: /bin/bash
      when: ansible_os_family == "Debian"

    - name: Install Python and curl for RedHat/Oracle
      raw: |
        yum install -y python3 curl
      changed_when: false
      args:
        executable: /bin/bash
      when: ansible_os_family == "RedHat"

    - name: Gather facts
      setup:
